"""Compatibility facade for bundle repository helpers."""

from .bundle_layout import (
    CANONICAL_EXPORT_GROUPS,
    CUSTOM_EXPORT_GROUP,
    EXPORT_GROUP_LABELS,
    EXPORT_GROUP_ORDER,
    KNOWN_BUNDLE_GROUPS,
    LEGACY_EXPORT_GROUP,
    LEGACY_EXPORT_GROUP_ALIASES,
    LEGACY_MACHINE_KEY,
    LEGACY_MACHINE_LABEL,
    LEGACY_ROOT_DIRS,
    bundle_export_group_label,
    canonical_export_group_name,
    infer_bundle_export_group,
    infer_bundle_machine,
    infer_bundle_project_metadata,
    load_project_export_metadata,
    source_group_allows_export_group,
)
from .bundle_repository import resolve_bundle_dir, resolve_known_bundle_dir
from .bundle_scanner import (
    bundle_directory_sort_key,
    collect_bundle_summaries,
    collect_known_bundle_summaries,
    iter_bundle_directories_under_root,
    iter_known_bundle_directories,
    latest_distinct_bundle_summaries,
)
from .bundle_validation import validate_bundle_directory

__all__ = [
    "CANONICAL_EXPORT_GROUPS",
    "CUSTOM_EXPORT_GROUP",
    "EXPORT_GROUP_LABELS",
    "EXPORT_GROUP_ORDER",
    "KNOWN_BUNDLE_GROUPS",
    "LEGACY_EXPORT_GROUP",
    "LEGACY_EXPORT_GROUP_ALIASES",
    "LEGACY_MACHINE_KEY",
    "LEGACY_MACHINE_LABEL",
    "LEGACY_ROOT_DIRS",
    "bundle_directory_sort_key",
    "bundle_export_group_label",
    "canonical_export_group_name",
    "collect_bundle_summaries",
    "collect_known_bundle_summaries",
    "infer_bundle_export_group",
    "infer_bundle_machine",
    "infer_bundle_project_metadata",
    "iter_bundle_directories_under_root",
    "iter_known_bundle_directories",
    "latest_distinct_bundle_summaries",
    "load_project_export_metadata",
    "resolve_bundle_dir",
    "resolve_known_bundle_dir",
    "source_group_allows_export_group",
    "validate_bundle_directory",
]
